// Bridge between the renderer UI and the main process.
const { contextBridge, ipcRenderer } = require("electron");

contextBridge.exposeInMainWorld("api", {
  listItems: () => ipcRenderer.invoke("items:list"),
  saveItems: (items) => ipcRenderer.invoke("items:save", items),
  showListing: (itemId, bounds, opts) => ipcRenderer.invoke("listing:show", { itemId, bounds, ...opts }),
  hideListing: () => ipcRenderer.invoke("listing:hide"),
  prefetchListing: (itemId) => ipcRenderer.invoke("listing:prefetch", itemId),
  listingOffers: (itemId) => ipcRenderer.invoke("listing:offers", itemId),
  zoomListing: (dir) => ipcRenderer.invoke("listing:zoom", dir),
  openExternal: (itemId) => ipcRenderer.invoke("listing:openExternal", itemId),
  onListingLoading: (cb) => ipcRenderer.on("listing:loading", (_e, loading) => cb(loading)),
  onListingNavigated: (cb) => ipcRenderer.on("listing:navigated", (_e, itemId) => cb(itemId)),
  onListingPrice: (cb) => ipcRenderer.on("listing:price", (_e, p) => cb(p)),
  listingPrice: () => ipcRenderer.invoke("listing:price"),
  readClipboard: () => ipcRenderer.invoke("clip:read"),
  writeClipboard: (t) => ipcRenderer.invoke("clip:write", t),
  importSheet: () => ipcRenderer.invoke("sheet:import"),
  saveImportTemplate: () => ipcRenderer.invoke("sheet:template"),
  exportSheet: (rows) => ipcRenderer.invoke("sheet:export", rows),
  exportRepricer: (payload) => ipcRenderer.invoke("sheet:exportRepricer", payload),
  exportIncentive: (payload) => ipcRenderer.invoke("sheet:exportIncentive", payload),
  appVersion: () => ipcRenderer.invoke("app:version"),
  checkForUpdates: (manual) => ipcRenderer.invoke("update:check", manual),
  downloadUpdate: () => ipcRenderer.invoke("update:download"),
  installUpdate: () => ipcRenderer.invoke("update:install"),
  updateState: () => ipcRenderer.invoke("update:state"),
  onUpdateState: (cb) => ipcRenderer.on("update:state", (_e, st) => cb(st)),
});
